### ISSUE TITLE
build failed

### ISSUE THREAD

**Issue by zhoushuntong** [hyperledger/avalon#465]
Setting up dirmngr (2.2.4-1ubuntu1.2) ...
Setting up build-essential (12.4ubuntu1) ...
Setting up gpg-wks-client (2.2.4-1ubuntu1.2) ...
Setting up gnupg (2.2.4-1ubuntu1.2) ...
Processing triggers for libc-bin (2.27-3ubuntu1) ...
Collecting json-rpc
  Downloading https://files.pythonhosted.org/packages/93/a4/c7da3efc17da87042e077f4587ad018ff20ada0de32f0189d1d7ccf403f8/json_rpc-1.13.0-py2.py3-none-any.whl (41kB)
Collecting pyzmq
  Downloading https://files.pythonhosted.org/packages/c9/11/bb28199dd8f186a4053b7dd94a33abf0c1162d99203e7ab32a6b71fa045b/pyzmq-19.0.1-cp36-cp36m-manylinux1_x86_64.whl (1.1MB)
Exception:
Traceback (most recent call last):
  File "/usr/share/python-wheels/urllib3-1.22-py2.py3-none-any.whl/urllib3/response.py", line 302, in _error_catcher
    yield
  File "/usr/share/python-wheels/urllib3-1.22-py2.py3-none-any.whl/urllib3/response.py", line 384, in read
    data = self._fp.read(amt)
  File "/usr/share/python-wheels/CacheControl-0.11.7-py2.py3-none-any.whl/cachecontrol/filewrapper.py", line 60, in read
    data = self.__fp.read(amt)
  File "/usr/lib/python3.6/http/client.py", line 459, in read
    n = self.readinto(b)
  File "/usr/lib/python3.6/http/client.py", line 503, in readinto
    n = self.fp.readinto(b)
  File "/usr/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib/python3.6/ssl.py", line 1012, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib/python3.6/ssl.py", line 874, in read
    return self._sslobj.read(len, buffer)
  File "/usr/lib/python3.6/ssl.py", line 631, in read
    v = self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/usr/lib/python3/dist-packages/pip/commands/install.py", line 353, in run
    wb.build(autobuilding=True)
  File "/usr/lib/python3/dist-packages/pip/wheel.py", line 749, in build
    self.requirement_set.prepare_files(self.finder)
  File "/usr/lib/python3/dist-packages/pip/req/req_set.py", line 380, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "/usr/lib/python3/dist-packages/pip/req/req_set.py", line 620, in _prepare_file
    session=self.session, hashes=hashes)
  File "/usr/lib/python3/dist-packages/pip/download.py", line 821, in unpack_url
    hashes=hashes
  File "/usr/lib/python3/dist-packages/pip/download.py", line 659, in unpack_http_url
    hashes)
  File "/usr/lib/python3/dist-packages/pip/download.py", line 882, in _download_http_url
    _download_url(resp, link, content_file, hashes)
  File "/usr/lib/python3/dist-packages/pip/download.py", line 603, in _download_url
    hashes.check_against_chunks(downloaded_chunks)
  File "/usr/lib/python3/dist-packages/pip/utils/hashes.py", line 46, in check_against_chunks
    for chunk in chunks:
  File "/usr/lib/python3/dist-packages/pip/download.py", line 571, in written_chunks
    for chunk in chunks:
  File "/usr/lib/python3/dist-packages/pip/utils/ui.py", line 139, in iter
    for x in it:
  File "/usr/lib/python3/dist-packages/pip/download.py", line 560, in resp_read
    decode_content=False):
  File "/usr/share/python-wheels/urllib3-1.22-py2.py3-none-any.whl/urllib3/response.py", line 436, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "/usr/share/python-wheels/urllib3-1.22-py2.py3-none-any.whl/urllib3/response.py", line 401, in read
    raise IncompleteRead(self._fp_bytes_read, self.length_remaining)
  File "/usr/lib/python3.6/contextlib.py", line 99, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/share/python-wheels/urllib3-1.22-py2.py3-none-any.whl/urllib3/response.py", line 307, in _error_catcher
    raise ReadTimeoutError(self._pool, None, 'Read timed out.')
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Read timed out.
ERROR: Service 'avalon-listener' failed to build: The command '/bin/sh -c apt-get update  && apt-get install -y -q python3-pip  && pip3 install json-rpc pyzmq && echo "Install Common Python, Crypto, Listener and SDK packages\n"  && pip3 install dist/*.whl  && echo "Remove unused packages from image\n"  && apt-get autoremove --purge -y -q python3-pip  && apt-get clean  && rm -rf /var/lib/apt/lists/*' returned a non-zero code: 2

**Comment by danintel** [comment]
Looks like you had network problems downloading a Python wheel package (*.whl).
You can verify this by trying to download the file manually.  That is, something like this:

```
$ wget https://files.pythonhosted.org/packages/c9/11/bb28199dd8f186
a4053b7dd94a33abf0c1162d99203e7ab32a6b71fa045b/pyzmq-19.0.1-cp36-cp36m-manylinu
x1_x86_64.whl 
--2020-05-14 15:37:10--  https://files.pythonhosted.org/packages/c9/11/bb28199dd8f186a4053b7dd94a33abf0c1162d99203e7ab32a6b71fa045b/pyzmq-19.0.1-cp36-cp36m-manylinux1_x86_64.whl
Resolving files.pythonhosted.org (files.pythonhosted.org)... 199.232.73.63, 2a04:4e42:52::319
Connecting to files.pythonhosted.org (files.pythonhosted.org)|199.232.73.63|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1070412 (1.0M) [application/octet-stream]
Saving to: ‘pyzmq-19.0.1-cp36-cp36m-manylinux1_x86_64.whl’
pyzmq-19.0.1-cp36-c 100%[===================>]   1.02M  --.-KB/s    in 0.04s   
2020-05-14 15:37:10 (24.7 MB/s) - ‘pyzmq-19.0.1-cp36-cp36m-manylinux1_x86_64.whl’ saved [1070412/1070412]
```

**Comment by pankajgoyal2** [comment]
> Looks like you had network problems downloading a Python wheel package (*.whl).
> You can verify this by trying to download the file manually. That is, something like this:
> 
> ```
> $ wget https://files.pythonhosted.org/packages/c9/11/bb28199dd8f186
> a4053b7dd94a33abf0c1162d99203e7ab32a6b71fa045b/pyzmq-19.0.1-cp36-cp36m-manylinu
> x1_x86_64.whl 
> --2020-05-14 15:37:10--  https://files.pythonhosted.org/packages/c9/11/bb28199dd8f186a4053b7dd94a33abf0c1162d99203e7ab32a6b71fa045b/pyzmq-19.0.1-cp36-cp36m-manylinux1_x86_64.whl
> Resolving files.pythonhosted.org (files.pythonhosted.org)... 199.232.73.63, 2a04:4e42:52::319
> Connecting to files.pythonhosted.org (files.pythonhosted.org)|199.232.73.63|:443... connected.
> HTTP request sent, awaiting response... 200 OK
> Length: 1070412 (1.0M) [application/octet-stream]
> Saving to: ‘pyzmq-19.0.1-cp36-cp36m-manylinux1_x86_64.whl’
> pyzmq-19.0.1-cp36-c 100%[===================>]   1.02M  --.-KB/s    in 0.04s   
> 2020-05-14 15:37:10 (24.7 MB/s) - ‘pyzmq-19.0.1-cp36-cp36m-manylinux1_x86_64.whl’ saved [1070412/1070412]
> ```

@zhoushuntong Did you try to download the file manually as suggested by @danintel ? Please update here!

**Comment by danintel** [comment]
No update here to make. It was most likely a network or network proxy issue and should be closed.

**Comment by rranjan3** [comment]
Closing issue for lack of response from reporter. Supposedly, it was a network proxy issue.
