### ISSUE TITLE
tests/Demo.py    request time out

### ISSUE THREAD

**Issue by zhoushuntong** [hyperledger/avalon#487]
| 2020-05-20 08:07:57,488 - INFO - b'L\nwo-timestamps'
avalon-sgx-enclave-manager    | File /tmp/account_ledger.json WRITE has been completed
avalon-sgx-enclave-manager    | 
avalon-lmdb                   | 2020-05-20 08:07:57,488 - INFO - ['L', 'wo-timestamps']
avalon-sgx-enclave-manager    | Avalon Intel SGX Enclave initialized.

[08:11:06 INFO    __main__] *********Request Json********* 
{"jsonrpc": "2.0", "method": "WorkerLookUp", "id": 1, "params": {"workerType": 1, "workOrderId": null}}

[08:11:16 ERROR   avalon_sdk.http_client.http_jrpc_client] no response from server: timed out
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/avalon_sdk/http_client/http_jrpc_client.py", line 62, in _postmsg
    response = opener.open(request, timeout=10)
  File "/usr/lib/python3.6/urllib/request.py", line 526, in open
    response = self._open(req, data)
  File "/usr/lib/python3.6/urllib/request.py", line 544, in _open
    '_open', req)
  File "/usr/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 1353, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "/usr/lib/python3.6/urllib/request.py", line 1328, in do_open
    r = h.getresponse()
  File "/usr/lib/python3.6/http/client.py", line 1356, in getresponse
    response.begin()
  File "/usr/lib/python3.6/http/client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.6/http/client.py", line 268, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
socket.timeout: timed out
[08:11:16 WARNING STDERR] Traceback (most recent call last):
[08:11:16 WARNING STDERR]   File "/usr/local/lib/python3.6/dist-packages/avalon_sdk/http_client/http_jrpc_client.py", line 62, in _postmsg
[08:11:16 WARNING STDERR] response = opener.open(request, timeout=10)
[08:11:16 WARNING STDERR]   File "/usr/lib/python3.6/urllib/request.py", line 526, in open
[08:11:16 WARNING STDERR] response = self._open(req, data)
[08:11:16 WARNING STDERR]   File "/usr/lib/python3.6/urllib/request.py", line 544, in _open
[08:11:16 WARNING STDERR] '_open', req)
[08:11:16 WARNING STDERR]   File "/usr/lib/python3.6/urllib/request.py", line 504, in _call_chain
[08:11:16 WARNING STDERR] result = func(*args)
[08:11:16 WARNING STDERR]   File "/usr/lib/python3.6/urllib/request.py", line 1353, in http_open
[08:11:16 WARNING STDERR] return self.do_open(http.client.HTTPConnection, req)
[08:11:16 WARNING STDERR]   File "/usr/lib/python3.6/urllib/request.py", line 1328, in do_open
[08:11:16 WARNING STDERR] r = h.getresponse()
[08:11:16 WARNING STDERR]   File "/usr/lib/python3.6/http/client.py", line 1356, in getresponse
[08:11:16 WARNING STDERR] response.begin()
[08:11:16 WARNING STDERR]   File "/usr/lib/python3.6/http/client.py", line 307, in begin
[08:11:16 WARNING STDERR] version, status, reason = self._read_status()
[08:11:16 WARNING STDERR]   File "/usr/lib/python3.6/http/client.py", line 268, in _read_status
[08:11:16 WARNING STDERR] line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
[08:11:16 WARNING STDERR]   File "/usr/lib/python3.6/socket.py", line 586, in readinto
[08:11:16 WARNING STDERR] return self._sock.recv_into(b)
[08:11:16 WARNING STDERR] socket
[08:11:16 WARNING STDERR] .
[08:11:16 WARNING STDERR] timeout
[08:11:16 WARNING STDERR] :
[08:11:16 WARNING STDERR] timed out
[08:11:16 WARNING STDERR] 
[08:11:16 WARNING STDERR] During handling of the above exception, another exception occurred:
[08:11:16 WARNING STDERR] Traceback (most recent call last):
[08:11:16 WARNING STDERR]   File "Demo.py", line 295, in <module>
[08:11:16 WARNING STDERR] Main()
[08:11:16 WARNING STDERR]   File "Demo.py", line 291, in Main
[08:11:16 WARNING STDERR] local_main(config)
[08:11:16 WARNING STDERR]   File "Demo.py", line 121, in local_main
[08:11:16 WARNING STDERR] response = uri_client._postmsg(input_json_str1)
[08:11:16 WARNING STDERR]   File "/usr/local/lib/python3.6/dist-packages/avalon_sdk/http_client/http_jrpc_client.py", line 75, in _postmsg
[08:11:16 WARNING STDERR] raise MessageException('no response from server: {0}'.format(err))
[08:11:16 WARNING STDERR] avalon_sdk.http_client.http_jrpc_client
[08:11:16 WARNING STDERR] .
[08:11:16 WARNING STDERR] MessageException
[08:11:16 WARNING STDERR] :
[08:11:16 WARNING STDERR] no response from server: timed out

**Comment by zhoushuntong** [comment]
root@513f6ffd6abe:/project/avalon# cd tests/
root@513f6ffd6abe:/project/avalon/tests# python3 Demo.py --input_dir ./json_requests/ \
>    --connect_uri "http://avalon-listener:1947" work_orders/output.json
[09:11:33 INFO    __main__] ***************** AVALON *****************
[09:11:33 INFO    __main__] Load Json Directory from ./json_requests/
[09:11:33 INFO    __main__] Execute work order
[09:11:33 INFO    __main__] ---------------- Input file name: json_01.json -------------

[09:11:33 INFO    __main__] *********Request Json********* 
{"jsonrpc": "2.0", "method": "WorkerLookUp", "id": 1, "params": {"workerType": 1, "workOrderId": null}}

[09:11:33 INFO    __main__] **********Received Response*********
{'result': {'totalCount': 1, 'lookupTag': '9198b192f48a1130ffd6ade55ef100d13435566824b54da8ff9fb9b54251f2b0', 'ids': ['9198b192f48a1130ffd6ade55ef100d13435566824b54da8ff9fb9b54251f2b0']}, 'id': 1, 'jsonrpc': '2.0'}

[09:11:33 INFO    __main__] ---------------- Input file name: json_02.json -------------

[09:11:33 INFO    __main__] ********** Worker details Updated with Worker ID*********
{"jsonrpc": "2.0", "method": "WorkerRetrieve", "id": 2, "params": {"workerId": "9198b192f48a1130ffd6ade55ef100d13435566824b54da8ff9fb9b54251f2b0"}}

[09:11:33 INFO    __main__] *********Request Json********* 
{"jsonrpc": "2.0", "method": "WorkerRetrieve", "id": 2, "params": {"workerId": "9198b192f48a1130ffd6ade55ef100d13435566824b54da8ff9fb9b54251f2b0", "workOrderId": null}}

[09:11:33 INFO    __main__] **********Received Response*********
{'result': {'workerType': 1, 'organizationId': 'aabbcc1234ddeeff', 'applicationTypeId': '11aa22bb33cc44dd', 'details': {'workOrderSyncUri': '', 'workOrderAsyncUri': '', 'workOrderPullUri': '', 'workOrderNotifyUri': '', 'receiptInvocationUri': '', 'workOrderInvocationAddress': '', 'receiptInvocationAddress': '', 'fromAddress': '', 'hashingAlgorithm': 'SHA-256', 'signingAlgorithm': 'SECP256K1', 'keyEncryptionAlgorithm': 'RSA-OAEP-3072', 'dataEncryptionAlgorithm': 'AES-GCM-256', 'workOrderPayloadFormats': 'JSON-RPC', 'workerTypeData': {'verificationKey': '-----BEGIN PUBLIC KEY-----\nMFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAE22rcJMnSl3SssGPpcccyrs8BgCqLI0ao\nt7RnpZ5UH62ij++iyGETFKc/6Y/OizZ3Q3phdRYutL1ItRoKeW386Q==\n-----END PUBLIC KEY-----\n', 'extendedMeasurements': ['A013D83D752EE0D25F8B51CDC2152D3500000000000000000000000000000000', '07BF68C754E465868FB843DBB4337771B82B081F3220C088D6E2B8CB5BADD69A'], 'proofDataType': 'TEE-SGX-IAS', 'proofData': '{"verification_report": "{\\"nonce\\":\\"BDD2D5654309648F83FD911456DAA485\\",\\"id\\":\\"248347472554349963098215156109978526964\\",\\"timestamp\\":\\"2020-05-20T09:10:03.093322\\",\\"version\\":3,\\"epidPseudonym\\":\\"WYrrOhuhfNEuvJ1miaC4jti0b5Gxhx4yXUSmAC+5uslkztlG0R17Ht/L7JlB7DDA0aH9H486sBoC2VMGADy4kNj37XwkahTdH+SVE0SA3Ll7goB5arICC1xZ8udgRQns0mhL09VgXSCM3sE7mv9MHGxV3hyrUKUbT92TZiO6k54=\\",\\"isvEnclaveQuoteStatus\\":\\"GROUP_OUT_OF_DATE\\",\\"platformInfoBlob\\":\\"1502006504000F00000E0E02040180070000000000000000000B00000B000000020000000000000B2F2BDDB36A86E231FB0C3BCD2185399EF9F9A683A3CAB01344FC19EE1A512AB0EB4CF3E1A93743AB29F8F62F355B478C3465A82468FFDA11214AF1398AF60EEA38\\",\\"isvEnclaveQuoteBody\\":\\"AgABAC8LAAAKAAkAAAAAAKAT2D11LuDSX4tRzcIVLTUAAAAAAAAAAAAAAAAAAAAABQ4CBQGAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABwAAAAAAAAAHAAAAAAAAAAe/aMdU5GWGj7hD27Qzd3G4KwgfMiDAiNbiuMtbrdaaAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB4xTH2y/FNwvxW5sNO4kRKMwIQCsnxAdSyz9PBA0B1dQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAOeQAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/yH+fntxDIjsPAU7q/XXVZDEpiPjKyIXgzCtM2bWBEgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\\"}", "ias_report_signature": "otskU4Uy7Tf2IDQUPv7E+d9B0QlMb1VP+4np7tmYEl7lUDYcGF+rVU95bBUz3NKTQbhmpKbMqiqMFAKSM/DF0FyK4aGSC7wHmzwngvyix1D0PUK7rwC7jJGB+aeggjI9jydRva+eW8U9iQvq8S54Rs7rACEqGuteQ17VLAedlzlTwrTfegVlxBXrGLfVQky/V3bdmBjtgZZYm836po4uKPH+CSobemGcOUkdAYrZ0gxvcfRmP3W950fczn8UySvI5p/A+6Y/9c1hq9hfrU9BjGa60Yu5ZdEC9xB/cHn2q226RSd0IghwR4UaMd4iURG2gt6deTaBrdkuE7NfgEe09w==", "ias_report_signing_certificate": "-----BEGIN CERTIFICATE-----\\nMIIEoTCCAwmgAwIBAgIJANEHdl0yo7CWMA0GCSqGSIb3DQEBCwUAMH4xCzAJBgNV\\nBAYTAlVTMQswCQYDVQQIDAJDQTEUMBIGA1UEBwwLU2FudGEgQ2xhcmExGjAYBgNV\\nBAoMEUludGVsIENvcnBvcmF0aW9uMTAwLgYDVQQDDCdJbnRlbCBTR1ggQXR0ZXN0\\nYXRpb24gUmVwb3J0IFNpZ25pbmcgQ0EwHhcNMTYxMTIyMDkzNjU4WhcNMjYxMTIw\\nMDkzNjU4WjB7MQswCQYDVQQGEwJVUzELMAkGA1UECAwCQ0ExFDASBgNVBAcMC1Nh\\nbnRhIENsYXJhMRowGAYDVQQKDBFJbnRlbCBDb3Jwb3JhdGlvbjEtMCsGA1UEAwwk\\nSW50ZWwgU0dYIEF0dGVzdGF0aW9uIFJlcG9ydCBTaWduaW5nMIIBIjANBgkqhkiG\\n9w0BAQEFAAOCAQ8AMIIBCgKCAQEAqXot4OZuphR8nudFrAFiaGxxkgma/Es/BA+t\\nbeCTUR106AL1ENcWA4FX3K+E9BBL0/7X5rj5nIgX/R/1ubhkKWw9gfqPG3KeAtId\\ncv/uTO1yXv50vqaPvE1CRChvzdS/ZEBqQ5oVvLTPZ3VEicQjlytKgN9cLnxbwtuv\\nLUK7eyRPfJW/ksddOzP8VBBniolYnRCD2jrMRZ8nBM2ZWYwnXnwYeOAHV+W9tOhA\\nImwRwKF/95yAsVwd21ryHMJBcGH70qLagZ7Ttyt++qO/6+KAXJuKwZqjRlEtSEz8\\ngZQeFfVYgcwSfo96oSMAzVr7V0L6HSDLRnpb6xxmbPdqNol4tQIDAQABo4GkMIGh\\nMB8GA1UdIwQYMBaAFHhDe3amfrzQr35CN+s1fDuHAVE8MA4GA1UdDwEB/wQEAwIG\\nwDAMBgNVHRMBAf8EAjAAMGAGA1UdHwRZMFcwVaBToFGGT2h0dHA6Ly90cnVzdGVk\\nc2VydmljZXMuaW50ZWwuY29tL2NvbnRlbnQvQ1JML1NHWC9BdHRlc3RhdGlvblJl\\ncG9ydFNpZ25pbmdDQS5jcmwwDQYJKoZIhvcNAQELBQADggGBAGcIthtcK9IVRz4r\\nRq+ZKE+7k50/OxUsmW8aavOzKb0iCx07YQ9rzi5nU73tME2yGRLzhSViFs/LpFa9\\nlpQL6JL1aQwmDR74TxYGBAIi5f4I5TJoCCEqRHz91kpG6Uvyn2tLmnIdJbPE4vYv\\nWLrtXXfFBSSPD4Afn7+3/XUggAlc7oCTizOfbbtOFlYA4g5KcYgS1J2ZAeMQqbUd\\nZseZCcaZZZn65tdqee8UXZlDvx0+NdO0LR+5pFy+juM0wWbu59MvzcmTXbjsi7HY\\n6zd53Yq5K244fwFHRQ8eOB0IWB+4PfM7FeAApZvlfqlKOlLcZL2uyVmzRkyR5yW7\\n2uo9mehX44CiPJ2fse9Y6eQtcfEhMPkmHXI01sN+KwPbpA39+xOsStjhP9N1Y1a2\\ntQAVo+yVgLgV2Hws73Fc0o3wC78qPEA+v2aRs/Be3ZFDgDyghc/1fgU+7C+P6kbq\\nd4poyb6IW8KCJbxfMJvkordNOgOUUxndPHEi/tb/U7uLjLOgPA==\\n-----END CERTIFICATE-----\\n-----BEGIN CERTIFICATE-----\\nMIIFSzCCA7OgAwIBAgIJANEHdl0yo7CUMA0GCSqGSIb3DQEBCwUAMH4xCzAJBgNV\\nBAYTAlVTMQswCQYDVQQIDAJDQTEUMBIGA1UEBwwLU2FudGEgQ2xhcmExGjAYBgNV\\nBAoMEUludGVsIENvcnBvcmF0aW9uMTAwLgYDVQQDDCdJbnRlbCBTR1ggQXR0ZXN0\\nYXRpb24gUmVwb3J0IFNpZ25pbmcgQ0EwIBcNMTYxMTE0MTUzNzMxWhgPMjA0OTEy\\nMzEyMzU5NTlaMH4xCzAJBgNVBAYTAlVTMQswCQYDVQQIDAJDQTEUMBIGA1UEBwwL\\nU2FudGEgQ2xhcmExGjAYBgNVBAoMEUludGVsIENvcnBvcmF0aW9uMTAwLgYDVQQD\\nDCdJbnRlbCBTR1ggQXR0ZXN0YXRpb24gUmVwb3J0IFNpZ25pbmcgQ0EwggGiMA0G\\nCSqGSIb3DQEBAQUAA4IBjwAwggGKAoIBgQCfPGR+tXc8u1EtJzLA10Feu1Wg+p7e\\nLmSRmeaCHbkQ1TF3Nwl3RmpqXkeGzNLd69QUnWovYyVSndEMyYc3sHecGgfinEeh\\nrgBJSEdsSJ9FpaFdesjsxqzGRa20PYdnnfWcCTvFoulpbFR4VBuXnnVLVzkUvlXT\\nL/TAnd8nIZk0zZkFJ7P5LtePvykkar7LcSQO85wtcQe0R1Raf/sQ6wYKaKmFgCGe\\nNpEJUmg4ktal4qgIAxk+QHUxQE42sxViN5mqglB0QJdUot/o9a/V/mMeH8KvOAiQ\\nbyinkNndn+Bgk5sSV5DFgF0DffVqmVMblt5p3jPtImzBIH0QQrXJq39AT8cRwP5H\\nafuVeLHcDsRp6hol4P+ZFIhu8mmbI1u0hH3W/0C2BuYXB5PC+5izFFh/nP0lc2Lf\\n6rELO9LZdnOhpL1ExFOq9H/B8tPQ84T3Sgb4nAifDabNt/zu6MmCGo5U8lwEFtGM\\nRoOaX4AS+909x00lYnmtwsDVWv9vBiJCXRsCAwEAAaOByTCBxjBgBgNVHR8EWTBX\\nMFWgU6BRhk9odHRwOi8vdHJ1c3RlZHNlcnZpY2VzLmludGVsLmNvbS9jb250ZW50\\nL0NSTC9TR1gvQXR0ZXN0YXRpb25SZXBvcnRTaWduaW5nQ0EuY3JsMB0GA1UdDgQW\\nBBR4Q3t2pn680K9+QjfrNXw7hwFRPDAfBgNVHSMEGDAWgBR4Q3t2pn680K9+Qjfr\\nNXw7hwFRPDAOBgNVHQ8BAf8EBAMCAQYwEgYDVR0TAQH/BAgwBgEB/wIBADANBgkq\\nhkiG9w0BAQsFAAOCAYEAeF8tYMXICvQqeXYQITkV2oLJsp6J4JAqJabHWxYJHGir\\nIEqucRiJSSx+HjIJEUVaj8E0QjEud6Y5lNmXlcjqRXaCPOqK0eGRz6hi+ripMtPZ\\nsFNaBwLQVV905SDjAzDzNIDnrcnXyB4gcDFCvwDFKKgLRjOB/WAqgscDUoGq5ZVi\\nzLUzTqiQPmULAQaB9c6Oti6snEFJiCQ67JLyW/E83/frzCmO5Ru6WjU4tmsmy8Ra\\nUd4APK0wZTGtfPXU7w+IBdG5Ez0kE1qzxGQaL4gINJ1zMyleDnbuS8UicjJijvqA\\n152Sq049ESDz+1rRGc2NVEqh1KaGXmtXvqxXcTB+Ljy5Bw2ke0v8iGngFBPqCTVB\\n3op5KBG3RjbF6RRSzwzuWfL7QErNC8WEy5yDVARzTA5+xmBc388v9Dm21HGfcC8O\\nDD+gT9sSpssq0ascmvH49MOgjt1yoysLtdCtJW/9FZpoOypaHx0R+mJTLwPXVMrv\\nDaVzWh5aiEx+idkSGMnX\\n-----END CERTIFICATE-----\\n"}', 'encryptionKey': '-----BEGIN RSA PUBLIC KEY-----\nMIIBCgKCAQEA3W0WcUDnUbGi6tKP3S0yChVlrx+2bn/xWdZ1NX342liWoNEOxKll\nyCCEfmp/au+XjVvIBF5uFn0K/d68o1tgG3ABXkfsxBS+MPXxgfWxcsi4UjyDRFNV\nupoLeug4ibChbiEoY6IZvehJpNFFsgZXZW5R2gNPoqeVHCZ828MncPy10RIgKtWG\nZtIfwHYM54LAiTrio6i7QeLey05RAQETYcTBjeYoFnsuz0qyDnQjE4xvRRTSdFln\nAkxCgOfSwuhDnq9ryseDMTwx1tqEDOVD2ANmzgeaJbxSylN2tcOCeLULNdpQixW+\n6/EMR2HgXikAcMFBid/Umv5BkG7w+jdE6wIDAQAB\n-----END RSA PUBLIC KEY-----\n', 'encryptionKeySignature': 'MEQCIEuh8UYf85hsWioCb4THhfEaXXffxcIhotS5StxCq782AiAiO9L/TyzJ73Cis730M4iN8KnOw0UsxHoPJQqqOGykXg=='}}, 'status': 1}, 'id': 2, 'jsonrpc': '2.0'}

[09:11:33 INFO    avalon_sdk.worker.worker_details] *********Updating Worker Details*********
[09:11:33 INFO    avalon_sdk.worker.worker_details] Hashing Algorithm : SHA-256
[09:11:33 INFO    avalon_sdk.worker.worker_details] Signing Algorithm : SECP256K1
[09:11:33 INFO    __main__] ---------------- Input file name: json_03.json -------------

[09:11:33 INFO    avalon_crypto_utils.signature] Encrypting Workorder Data
[09:11:33 INFO    avalon_crypto_utils.signature] Request Json successfully Signed
[09:11:33 INFO    __main__] *********Request Json********* 
{"jsonrpc": "2.0", "method": "WorkOrderSubmit", "id": 11, "params": {"responseTimeoutMSecs": 6000, "payloadFormat": "JSON-RPC", "resultUri": "resulturi", "notifyUri": "notifyuri", "workOrderId": "0xdd52de1a85ce8345", "workerId": "9198b192f48a1130ffd6ade55ef100d13435566824b54da8ff9fb9b54251f2b0", "workloadId": "68656172742d646973656173652d6576616c", "requesterId": "0x3456", "dataEncryptionAlgorithm": "AES-GCM-256", "encryptedSessionKey": "8602ea432f56d0a2eb1ea248bdcf27579c3b52aa6fbe6936628e952a7da35b13f93de413efc7a69b658fbddc118ceba125e47f1f7187e4efadd18817c6ca3a24cd33ca28f9906be10b73f6a754c58654515431f1d317e4baf60fa4898c2c79f971837e644f9b4b95021fff38e33f450aef3e6c13bd3303279eb58d77c5167ff1b94430b154d1fa9fd61ed60eb63e30bd76d568325e3bb95a72fbee6b9b8668006ccf51b33b9f5ea1d7cc1c88087cc9a4f09bfcdabf372becfd74b0964d12791b9a97c8abe14419183b34bfbdef9f524a2ce73c5603092cba69718052ec805fe6f7ebc5a02cf13c57ee225c083a9b8d54b14db788af68f0cce4e4b85970455444", "sessionKeyIv": "2d67ea10cf55680164a9f876", "requesterNonce": "4fab1ec56e1a82bed547c6c4d698d9b6", "encryptedRequestHash": "2e8d11078e6f01a4c558e82450c5f7caa01580bc047afdbd6cdc03aa15cd9c90093dd71925bb5bbfb41f8f52a1bb7ff3", "requesterSignature": "MEQCIH9NHPICmZBaJYbsiIoANvJMPepc7AfVc41ACb6b0kyGAiAytGvijzA1qqZFqeaIfoxGZTqqwVIG/MOKDBr7ay7HIw==", "inData": [{"index": 1, "data": "KsW9PGXtO/sXB4nQdHVVnRlETqloow1BnMN8C25JyeF6NA/4E1uzqRCrcyfm7NdjK4TTJoj7jEGMZVGVRW9pfHc2ej4dvS7pzTdlBe+CZly1CUMI", "encryptedDataEncryptionKey": "", "iv": ""}, {"index": 2, "data": "KsW9PGXtO/sXB4nQdHVVnRlETqloow1BnMN8C25JyeB9NA/oAkqiqhGrcyfl7NdjK4TTJoj7jEGZdECVRW9pfGYlaTn+nk7JKWSfHZ/pQrS93sgW1ss=", "encryptedDataEncryptionKey": "", "iv": ""}], "verifyingKey": "-----BEGIN PUBLIC KEY-----\nMFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEaPeLtTj7cLba9h7D07zTO6bB9yxtqT9V\nKamf7VhTx0bjx/zHnmDtUh7QI775AQ85N/ariDBluoykT2rX+X9Zsg==\n-----END PUBLIC KEY-----\n"}}

[09:11:43 ERROR   avalon_sdk.http_client.http_jrpc_client] no response from server: timed out
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/avalon_sdk/http_client/http_jrpc_client.py", line 62, in _postmsg
    response = opener.open(request, timeout=10)
  File "/usr/lib/python3.6/urllib/request.py", line 526, in open
    response = self._open(req, data)
  File "/usr/lib/python3.6/urllib/request.py", line 544, in _open
    '_open', req)
  File "/usr/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 1353, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "/usr/lib/python3.6/urllib/request.py", line 1328, in do_open
    r = h.getresponse()
  File "/usr/lib/python3.6/http/client.py", line 1356, in getresponse
    response.begin()
  File "/usr/lib/python3.6/http/client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.6/http/client.py", line 268, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
socket.timeout: timed out
[09:11:43 WARNING STDERR] Traceback (most recent call last):
[09:11:43 WARNING STDERR]   File "/usr/local/lib/python3.6/dist-packages/avalon_sdk/http_client/http_jrpc_client.py", line 62, in _postmsg
[09:11:43 WARNING STDERR] response = opener.open(request, timeout=10)
[09:11:43 WARNING STDERR]   File "/usr/lib/python3.6/urllib/request.py", line 526, in open
[09:11:43 WARNING STDERR] response = self._open(req, data)
[09:11:43 WARNING STDERR]   File "/usr/lib/python3.6/urllib/request.py", line 544, in _open
[09:11:43 WARNING STDERR] '_open', req)
[09:11:43 WARNING STDERR]   File "/usr/lib/python3.6/urllib/request.py", line 504, in _call_chain
[09:11:43 WARNING STDERR] result = func(*args)
[09:11:43 WARNING STDERR]   File "/usr/lib/python3.6/urllib/request.py", line 1353, in http_open
[09:11:43 WARNING STDERR] return self.do_open(http.client.HTTPConnection, req)
[09:11:43 WARNING STDERR]   File "/usr/lib/python3.6/urllib/request.py", line 1328, in do_open
[09:11:43 WARNING STDERR] r = h.getresponse()
[09:11:43 WARNING STDERR]   File "/usr/lib/python3.6/http/client.py", line 1356, in getresponse
[09:11:43 WARNING STDERR] response.begin()
[09:11:43 WARNING STDERR]   File "/usr/lib/python3.6/http/client.py", line 307, in begin
[09:11:43 WARNING STDERR] version, status, reason = self._read_status()
[09:11:43 WARNING STDERR]   File "/usr/lib/python3.6/http/client.py", line 268, in _read_status
[09:11:43 WARNING STDERR] line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
[09:11:43 WARNING STDERR]   File "/usr/lib/python3.6/socket.py", line 586, in readinto
[09:11:43 WARNING STDERR] return self._sock.recv_into(b)
[09:11:43 WARNING STDERR] socket
[09:11:43 WARNING STDERR] .
[09:11:43 WARNING STDERR] timeout
[09:11:43 WARNING STDERR] :
[09:11:43 WARNING STDERR] timed out
[09:11:43 WARNING STDERR] 
[09:11:43 WARNING STDERR] During handling of the above exception, another exception occurred:
[09:11:43 WARNING STDERR] Traceback (most recent call last):
[09:11:43 WARNING STDERR]   File "Demo.py", line 295, in <module>
[09:11:43 WARNING STDERR] Main()
[09:11:43 WARNING STDERR]   File "Demo.py", line 291, in Main
[09:11:43 WARNING STDERR] local_main(config)
[09:11:43 WARNING STDERR]   File "Demo.py", line 121, in local_main
[09:11:43 WARNING STDERR] response = uri_client._postmsg(input_json_str1)
[09:11:43 WARNING STDERR]   File "/usr/local/lib/python3.6/dist-packages/avalon_sdk/http_client/http_jrpc_client.py", line 75, in _postmsg
[09:11:43 WARNING STDERR] raise MessageException('no response from server: {0}'.format(err))
[09:11:43 WARNING STDERR] avalon_sdk.http_client.http_jrpc_client
[09:11:43 WARNING STDERR] .
[09:11:43 WARNING STDERR] MessageException
[09:11:43 WARNING STDERR] :
[09:11:43 WARNING STDERR] no response from server: timed out

**Comment by pankajgoyal2** [comment]
I tried to run this and could not reproduce this issue on latest avalon "master" branch. Please check and confirm.
