### ISSUE TITLE
core dumped  enclave_manager --lmdb_url http://avalon-lmdb:9090

### ISSUE THREAD

**Issue by jiahuigeng** [hyperledger/avalon#735]
for running docker-compose setting, I got such error:
avalon-enclave-manager    | 
avalon-lmdb               | 2020-12-28 11:31:01,217 - INFO - ['L', 'workers']
avalon-enclave-manager    | bash: line 2:     8 Illegal instruction     (core dumped) enclave_manager --lmdb_url http://avalon-lmdb:9090
avalon-lmdb               | 2020-12-28 11:31:01,217 - INFO - response[text/plain; charset=utf-8]: b'n'
avalon-lmdb               | 2020-12-28 11:31:01,219 - INFO - Received a new request from the client
avalon-lmdb               | 2020-12-28 11:31:01,220 - INFO - b'L\nregistries'
avalon-lmdb               | 2020-12-28 11:31:01,220 - INFO - ['L', 'registries']
avalon-lmdb               | 2020-12-28 11:31:01,220 - INFO - response[text/plain; charset=utf-8]: b'l\nregid'

if I run  python3 Demo.py --input_dir ./json_requests/    --connect_uri "http://avalon-listener:1947" work_orders/output.json

then 
[11:34:17 WARNING STDERR] Traceback (most recent call last):
[11:34:17 WARNING STDERR]   File "Demo.py", line 336, in <module>
[11:34:17 WARNING STDERR] Main()
[11:34:17 WARNING STDERR]   File "Demo.py", line 332, in Main
[11:34:17 WARNING STDERR] local_main(config)
[11:34:17 WARNING STDERR]   File "Demo.py", line 78, in local_main
[11:34:17 WARNING STDERR] input_json_obj["params"]["workerId"] = worker_id
[11:34:17 WARNING STDERR] UnboundLocalError
[11:34:17 WARNING STDERR] :
[11:34:17 WARNING STDERR] local variable 'worker_id' referenced before assignment

Can anyone help me?

**Comment by rranjan3** [comment]
Closing for merged fix #743 .
