### ISSUE TITLE
Testing Proxy Model with Fabric failed

### ISSUE THREAD

**Issue by kunmel** [hyperledger/avalon#760]
Followed the **TestingFabricProxyModel.rst**, get error running ```./generic_client.py -b fabric --workload_id "echo-result" --in_data "Hello" -o --worker_id "singleton-worker-1"``` in avalon-shell container. 
It can't resolve the DNS of the peers in fabric and i failed to ping the ip address of peer1.org0.example.com(172.26.0.2)

Error log:
```
Traceback (most recent call last):
  File "./generic_client.py", line 390, in <module>
    Main()
  File "./generic_client.py", line 264, in Main
    parser.get_blockchain_type())
  File "/project/avalon/examples/apps/generic_client/proxy_model_generic_client.py", line 46, in __init__
    self._worker_instance = FabricWorkerRegistryImpl(self._config)
  File "/usr/local/lib/python3.6/dist-packages/avalon_sdk/connector/blockchains/fabric/fabric_worker_registry.py", line 52, in __init__
    self.__fabric_wrapper = FabricWrapper(config)
  File "/usr/local/lib/python3.6/dist-packages/avalon_sdk/connector/blockchains/fabric/fabric_wrapper.py", line 73, in __init__
    self.__peername, 'Admin')
  File "/usr/local/lib/python3.6/dist-packages/avalon_sdk/connector/blockchains/fabric/tx_committer.py", line 40, in __init__
    org_name, peer_name, user_name)
  File "/usr/local/lib/python3.6/dist-packages/avalon_sdk/connector/blockchains/fabric/base.py", line 75, in __init__
    self._user, peer, self._channel_name))
  File "/usr/lib/python3.6/asyncio/base_events.py", line 484, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.6/dist-packages/hfc/fabric/client.py", line 169, in init_with_discovery
    local=False)
  File "/usr/local/lib/python3.6/dist-packages/aiogrpc/channel.py", line 40, in __call__
    return await fut
grpc._channel._MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "DNS resolution failed for service: peer2.org1.example.com:7051"
	debug_error_string = "{"created":"@1616589872.258401781","description":"Resolver transient failure","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":2141,"referenced_errors":[{"created":"@1616589872.258401199","description":"DNS resolution failed for service: peer2.org1.example.com:7051","file":"src/core/ext/filters/client_channel/resolver/dns/c_ares/dns_resolver_ares.cc","file_line":371,"grpc_status":14,"referenced_errors":[{"created":"@1616589872.258390108","description":"C-ares status is not ARES_SUCCESS qtype=A name=peer2.org1.example.com is_balancer=0: Domain name not found","file":"src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_wrapper.cc","file_line":728}]}]}"

```

**Comment by kunmel** [comment]
It is caused by iptables in docker, the avalon-shell and peers are in different docker networks, so they cant connect. After I set the iptables by ```sudo iptables -I DOCKER-USER -i br-818b626d02a4 -o br-6f342963b2c4 -j ACCEPT```, it's solved.
