### ISSUE TITLE
Docker build fails

### ISSUE THREAD

**Issue by SamYuan1990** [hyperledger/avalon#776]
```
executor failed running [/bin/sh -c python3 -m solcx.install v0.5.15]: exit code: 1
ERROR: Service 'avalon-shell' failed to build : Build failed
```

```
avalon % docker-compose up --build
Building avalon-lmdb
[+] Building 2.4s (22/22) FINISHED                                                                                            
 => [internal] load build definition from Dockerfile                                                                     0.0s
 => => transferring dockerfile: 3.88kB                                                                                   0.0s
 => [internal] load .dockerignore                                                                                        0.0s
 => => transferring context: 35B                                                                                         0.0s
 => [internal] load metadata for docker.io/library/ubuntu:bionic                                                         2.2s
 => [internal] load build context                                                                                        0.0s
 => => transferring context: 115.29kB                                                                                    0.0s
 => [base_image 1/4] FROM docker.io/library/ubuntu:bionic@sha256:0fedbd5bd9fb72089c7bbca476949e10593cebed9b1fb9edf5b79d  0.0s
 => CACHED [base_image 2/4] COPY ./scripts/install_packages /project/avalon/scripts/                                     0.0s
 => CACHED [base_image 3/4] RUN packages="curl wget";     pip_packages="";     if [ "bionic" = "bionic" ] ; then         0.0s
 => CACHED [base_image 4/4] RUN ln -sf /usr/bin/python3 /usr/bin/python                                                  0.0s
 => CACHED [build_image 1/9] COPY ./scripts/install_packages /project/avalon/scripts/                                    0.0s
 => CACHED [final_image 2/5] WORKDIR /project/avalon/shared_kv_storage/                                                  0.0s
 => CACHED [build_image 2/9] RUN packages="pkg-config cmake make python3-pip swig";     pip_packages="setuptools";       0.0s
 => CACHED [build_image 3/9] COPY VERSION /project/avalon/                                                               0.0s
 => CACHED [build_image 4/9] COPY ./bin /project/avalon/bin                                                              0.0s
 => CACHED [build_image 5/9] COPY ./common/cpp /project/avalon/common/cpp                                                0.0s
 => CACHED [build_image 6/9] COPY ./shared_kv_storage /project/avalon/shared_kv_storage                                  0.0s
 => CACHED [build_image 7/9] RUN cd /project/avalon/shared_kv_storage/db_store/packages    && mkdir -p build    && cd b  0.0s
 => CACHED [build_image 8/9] WORKDIR /project/avalon/shared_kv_storage/                                                  0.0s
 => CACHED [build_image 9/9] RUN echo "Building avalon Shared KV"    && make                                             0.0s
 => CACHED [final_image 3/5] COPY --from=build_image /project/avalon/shared_kv_storage/dist/*.whl dist/                  0.0s
 => CACHED [final_image 4/5] COPY --from=build_image /project/avalon/shared_kv_storage/lmdb_config.toml      lmdb_confi  0.0s
 => CACHED [final_image 5/5] RUN packages="";     pip_packages="coverage";     if [ "bionic" = "bionic" ] ; then         0.0s
 => exporting to image                                                                                                   0.0s
 => => exporting layers                                                                                                  0.0s
 => => writing image sha256:e7d7c6de6844544b44e3080401360892cea91f0dbd97c758cb6e5369f390eb38                             0.0s
 => => naming to docker.io/library/avalon-lmdb-dev                                                                       0.0s

Use 'docker scan' to run Snyk tests against images to find vulnerabilities and learn how to fix them
Building avalon-enclave-manager
[+] Building 1.8s (69/69) FINISHED                                                                                            
 => [internal] load build definition from Dockerfile                                                                     0.0s
 => => transferring dockerfile: 12.89kB                                                                                  0.0s
 => [internal] load .dockerignore                                                                                        0.0s
 => => transferring context: 35B                                                                                         0.0s
 => [internal] load metadata for docker.io/library/ubuntu:bionic                                                         1.5s
 => [internal] load build context                                                                                        0.1s
 => => transferring context: 2.67MB                                                                                      0.1s
 => [python_image 1/3] FROM docker.io/library/ubuntu:bionic@sha256:0fedbd5bd9fb72089c7bbca476949e10593cebed9b1fb9edf5b7  0.0s
 => CACHED [python_image 2/3] COPY ./scripts/install_packages /project/avalon/scripts/                                   0.0s
 => CACHED [base_image 3/4] RUN packages="";     pip_packages="";     if [ "bionic" = "bionic" ] ; then       DEBIAN_FR  0.0s
 => CACHED [base_image 4/4] RUN ln -sf /usr/bin/python3 /usr/bin/python                                                  0.0s
 => CACHED [build_image  1/47] COPY ./scripts/install_packages /project/avalon/scripts/                                  0.0s
 => CACHED [build_image  2/47] RUN packages="pkg-config cmake make git swig wget tar curl unzip"     && pip_packages="s  0.0s
 => CACHED [build_image  3/47] RUN if [ "bionic" = "centos" ] ; then       dnf -y --enablerepo=powertools install proto  0.0s
 => CACHED [build_image  4/47] RUN mkdir -p /opt/intel  && mkdir -p /etc/init                                            0.0s
 => CACHED [build_image  5/47] WORKDIR /opt/intel                                                                        0.0s
 => CACHED [build_image  6/47] RUN if [ "bionic" = "bionic" ] ; then       echo 'deb [arch=amd64] https://download.01.o  0.0s
 => CACHED [build_image  7/47] COPY docker/pccs/sgx_default_qcnl.conf /etc/sgx_default_qcnl.conf                         0.0s
 => CACHED [openssl_image 3/6] RUN packages="ca-certificates pkg-config make wget tar";     if [ "bionic" = "centos" ]   0.0s
 => CACHED [openssl_image 4/6] WORKDIR /tmp                                                                              0.0s
 => CACHED [openssl_image 5/6] RUN OPENSSL_VER=1.1.1g  && wget https://www.openssl.org/source/openssl-$OPENSSL_VER.tar.  0.0s
 => CACHED [openssl_image 6/6] RUN if [ "bionic" = "bionic" ] ; then       mkdir /usr/local/lib64;     fi                0.0s
 => CACHED [build_image  8/47] COPY --from=openssl_image /usr/local/ssl /usr/local/ssl                                   0.0s
 => CACHED [build_image  9/47] COPY --from=openssl_image /usr/local/bin /usr/local/bin                                   0.0s
 => CACHED [build_image 10/47] COPY --from=openssl_image /usr/local/include /usr/local/include                           0.0s
 => CACHED [build_image 11/47] COPY --from=openssl_image /usr/local/lib /usr/local/lib                                   0.0s
 => CACHED [build_image 12/47] COPY --from=openssl_image /usr/local/lib64 /usr/local/lib64                               0.0s
 => CACHED [build_image 13/47] COPY --from=openssl_image /tmp/openssl-1.1.1g.tar.gz /tmp/                                0.0s
 => CACHED [build_image 14/47] WORKDIR /tmp                                                                              0.0s
 => CACHED [build_image 15/47] RUN platform="";     if [ "bionic" = "bionic" ] ; then       platform="ubuntu18.04";      0.0s
 => CACHED [build_image 16/47] RUN rm -rf /project/avalon/tools/build/_dev                                               0.0s
 => CACHED [python_image 3/3] RUN packages="pkg-config python3-pip make"     pip_packages="setuptools";     if [ "bioni  0.0s
 => CACHED [avalon_sdk_image 1/5] COPY VERSION /project/avalon/                                                          0.0s
 => CACHED [avalon_sdk_image 2/5] COPY ./bin /project/avalon/bin                                                         0.0s
 => CACHED [common_python_image 3/5] COPY ./common/python /project/avalon/common/python                                  0.0s
 => CACHED [common_python_image 4/5] WORKDIR /project/avalon/common/python                                               0.0s
 => CACHED [common_python_image 5/5] RUN echo "Building Avalon Common Python\n"  && make                                 0.0s
 => CACHED [build_image 17/47] COPY --from=common_python_image /project/avalon/common/python/dist/*.whl dist/            0.0s
 => CACHED [avalon_sdk_image 3/5] COPY ./sdk /project/avalon/sdk                                                         0.0s
 => CACHED [avalon_sdk_image 4/5] WORKDIR /project/avalon/sdk                                                            0.0s
 => CACHED [avalon_sdk_image 5/5] RUN echo "Building Avalon SDK\n"  && make                                              0.0s
 => CACHED [build_image 18/47] COPY --from=avalon_sdk_image /project/avalon/sdk/dist/*.whl dist/                         0.0s
 => CACHED [build_image 19/47] RUN echo "Install common/python and sdk packages\n"  && pip3 install dist/*.whl json-rpc  0.0s
 => CACHED [build_image 20/47] RUN openssl genrsa -3 -out /project/avalon/enclave.pem 3072                               0.0s
 => CACHED [build_image 21/47] COPY ./examples/apps /project/avalon/examples/apps                                        0.0s
 => CACHED [build_image 22/47] COPY ./common/cpp /project/avalon/common/cpp                                              0.0s
 => CACHED [build_image 23/47] COPY ./tc/sgx/trusted_worker_manager/enclave/kme/workload /project/avalon/tc/sgx/trusted  0.0s
 => CACHED [build_image 24/47] COPY ./tc/sgx/trusted_worker_manager /project/avalon/tc/sgx/trusted_worker_manager        0.0s
 => CACHED [build_image 25/47] COPY ./common/crypto_utils /project/avalon/common/crypto_utils                            0.0s
 => CACHED [build_image 26/47] COPY ./enclave_manager /project/avalon/enclave_manager                                    0.0s
 => CACHED [build_image 27/47] COPY ./common/sgx_workload /project/avalon/common/sgx_workload                            0.0s
 => CACHED [build_image 28/47] COPY ./bin /project/avalon/bin                                                            0.0s
 => CACHED [build_image 29/47] COPY ./VERSION /project/avalon/VERSION                                                    0.0s
 => CACHED [build_image 30/47] COPY ./scripts/generate_mrenclave.sh /project/avalon/scripts/generate_mrenclave.sh        0.0s
 => CACHED [build_image 31/47] COPY ./config /project/avalon/config                                                      0.0s
 => CACHED [build_image 32/47] WORKDIR /project/avalon/common/sgx_workload                                               0.0s
 => CACHED [build_image 33/47] RUN mkdir -p build   && cd build   && cmake ..   && make                                  0.0s
 => CACHED [build_image 34/47] RUN if [ "singleton" != "kme" ] ; then         cd /project/avalon/examples/apps;          0.0s
 => CACHED [build_image 35/47] RUN if [ "singleton" = "kme" ] ; then         cd /project/avalon/tc/sgx/trusted_worker_m  0.0s
 => CACHED [build_image 36/47] WORKDIR /project/avalon/common/cpp                                                        0.0s
 => CACHED [build_image 37/47] RUN mkdir -p build   && cd build   && cmake ..   && make                                  0.0s
 => CACHED [build_image 38/47] WORKDIR /project/avalon/tc/sgx/trusted_worker_manager/common                              0.0s
 => CACHED [build_image 39/47] RUN mkdir -p build   && cd build   && cmake ..   && make                                  0.0s
 => CACHED [build_image 40/47] WORKDIR /project/avalon/tc/sgx/trusted_worker_manager/enclave                             0.0s
 => CACHED [build_image 41/47] RUN mkdir -p build   && cd build   && cmake ..   && make                                  0.0s
 => CACHED [build_image 42/47] WORKDIR /project/avalon/tc/sgx/trusted_worker_manager/enclave_untrusted/enclave_bridge    0.0s
 => CACHED [build_image 43/47] RUN mkdir -p build   && cd build   && cmake ..   && make                                  0.0s
 => CACHED [build_image 44/47] WORKDIR /project/avalon/common/crypto_utils                                               0.0s
 => CACHED [build_image 45/47] RUN make && make install                                                                  0.0s
 => CACHED [build_image 46/47] WORKDIR /project/avalon/enclave_manager                                                   0.0s
 => CACHED [build_image 47/47] RUN echo "Build and Install avalon enclave manager"   && make && make install             0.0s
 => exporting to image                                                                                                   0.1s
 => => exporting layers                                                                                                  0.0s
 => => writing image sha256:649ba65c3207a54df19c73e9f7595b1df56180da96923a69453cfdee9d22068d                             0.0s
 => => naming to docker.io/library/avalon-enclave-manager-dev                                                            0.0s

Use 'docker scan' to run Snyk tests against images to find vulnerabilities and learn how to fix them
Building avalon-listener
[+] Building 1.9s (34/34) FINISHED                                                                                            
 => [internal] load build definition from Dockerfile                                                                     0.0s
 => => transferring dockerfile: 5.14kB                                                                                   0.0s
 => [internal] load .dockerignore                                                                                        0.0s
 => => transferring context: 35B                                                                                         0.0s
 => [internal] load metadata for docker.io/library/ubuntu:bionic                                                         1.7s
 => [internal] load build context                                                                                        0.0s
 => => transferring context: 87.81kB                                                                                     0.0s
 => [base_image 1/4] FROM docker.io/library/ubuntu:bionic@sha256:0fedbd5bd9fb72089c7bbca476949e10593cebed9b1fb9edf5b79d  0.0s
 => CACHED [base_image 2/4] COPY ./scripts/install_packages /project/avalon/scripts/                                     0.0s
 => CACHED [base_image 3/4] RUN packages="";     pip_packages="";     if [ "bionic" = "bionic" ] ; then       DEBIAN_FR  0.0s
 => CACHED [base_image 4/4] RUN ln -sf /usr/bin/python3 /usr/bin/python                                                  0.0s
 => CACHED [final_image 1/9] COPY ./scripts/install_packages /project/avalon/scripts/                                    0.0s
 => CACHED [final_image 2/9] WORKDIR /project/avalon/listener                                                            0.0s
 => CACHED [final_image 3/9] COPY ./listener/listener_config.toml /project/avalon/listener/listener_config.toml          0.0s
 => CACHED [final_image 4/9] COPY ./config/tcs_config.toml /project/avalon/config/                                       0.0s
 => CACHED [python_image 3/3] RUN packages="pkg-config python3-pip make"     pip_packages="setuptools";     if [ "bioni  0.0s
 => CACHED [build_image 1/6] COPY VERSION /project/avalon/                                                               0.0s
 => CACHED [build_image 2/6] COPY ./bin /project/avalon/bin                                                              0.0s
 => CACHED [common_python_image 3/5] COPY ./common/python /project/avalon/common/python                                  0.0s
 => CACHED [common_python_image 4/5] WORKDIR /project/avalon/common/python                                               0.0s
 => CACHED [common_python_image 5/5] RUN echo "Building Avalon Common Python\n"  && make                                 0.0s
 => CACHED [final_image 5/9] COPY --from=common_python_image /project/avalon/common/python/dist/*.whl dist/              0.0s
 => CACHED [common_crypto_utils_image 3/5] COPY ./common/crypto_utils /project/avalon/common/crypto_utils                0.0s
 => CACHED [common_crypto_utils_image 4/5] WORKDIR /project/avalon/common/crypto_utils                                   0.0s
 => CACHED [common_crypto_utils_image 5/5] RUN echo "Building Avalon Common Crypto Python\n"  && make                    0.0s
 => CACHED [final_image 6/9] COPY --from=common_crypto_utils_image /project/avalon/common/crypto_utils/dist/*.whl dist/  0.0s
 => CACHED [avalon_sdk_image 3/5] COPY ./sdk /project/avalon/sdk                                                         0.0s
 => CACHED [avalon_sdk_image 4/5] WORKDIR /project/avalon/sdk                                                            0.0s
 => CACHED [avalon_sdk_image 5/5] RUN echo "Building Avalon SDK\n"  && make                                              0.0s
 => CACHED [final_image 7/9] COPY --from=avalon_sdk_image /project/avalon/sdk/dist/*.whl dist/                           0.0s
 => CACHED [build_image 3/6] COPY ./config/tcs_config.toml /project/avalon/config/                                       0.0s
 => CACHED [build_image 4/6] COPY ./listener /project/avalon/listener                                                    0.0s
 => CACHED [build_image 5/6] WORKDIR /project/avalon/listener/                                                           0.0s
 => CACHED [build_image 6/6] RUN echo "Building avalon listener\n"   && make                                             0.0s
 => CACHED [final_image 8/9] COPY --from=build_image /project/avalon/listener/dist/*.whl dist/                           0.0s
 => CACHED [final_image 9/9] RUN packages="";     pip_packages="json-rpc pyzmq jsonschema coverage pycryptodomex ecdsa"  0.0s
 => exporting to image                                                                                                   0.0s
 => => exporting layers                                                                                                  0.0s
 => => writing image sha256:e34b4e4f76254cea7d7a7f02e19a545de105c34afdd78bd63c688c9517c68d56                             0.0s
 => => naming to docker.io/library/avalon-listener-dev                                                                   0.0s

Use 'docker scan' to run Snyk tests against images to find vulnerabilities and learn how to fix them
Building avalon-shell
[+] Building 2.4s (63/79)                                                                                                     
 => [internal] load build definition from Dockerfile                                                                     0.0s
 => => transferring dockerfile: 13.76kB                                                                                  0.0s
 => [internal] load .dockerignore                                                                                        0.0s
 => => transferring context: 35B                                                                                         0.0s
 => [internal] load metadata for docker.io/library/ubuntu:bionic                                                         1.4s
 => [internal] load build context                                                                                        0.3s
 => => transferring context: 1.71MB                                                                                      0.3s
 => [common_cpp_image  1/16] FROM docker.io/library/ubuntu:bionic@sha256:0fedbd5bd9fb72089c7bbca476949e10593cebed9b1fb9  0.0s
 => CACHED [common_cpp_image  2/16] COPY ./scripts/install_packages /project/avalon/scripts/                             0.0s
 => CACHED [python_image 3/3] RUN packages="ca-certificates pkg-config python3-pip make wget tar"     pip_packages="set  0.0s
 => CACHED [avalon_sdk_image 1/5] COPY VERSION /project/avalon/                                                          0.0s
 => CACHED [avalon_sdk_image 2/5] COPY ./bin /project/avalon/bin                                                         0.0s
 => CACHED [common_python_image 3/5] COPY ./common/python /project/avalon/common/python                                  0.0s
 => CACHED [common_python_image 4/5] WORKDIR /project/avalon/common/python                                               0.0s
 => CACHED [common_python_image 5/5] RUN echo "Building Avalon Common Python\n"  && make                                 0.0s
 => CACHED [avalon_sdk_image 3/5] COPY ./sdk /project/avalon/sdk                                                         0.0s
 => CACHED [avalon_sdk_image 4/5] WORKDIR /project/avalon/sdk                                                            0.0s
 => CACHED [avalon_sdk_image 5/5] RUN echo "Building Avalon SDK\n"  && make                                              0.0s
 => CACHED [base_image 3/4] RUN packages="wget tar";     pip_packages="";     if [ "bionic" = "bionic" ] ; then       D  0.0s
 => CACHED [base_image 4/4] RUN ln -sf /usr/bin/python3 /usr/bin/python                                                  0.0s
 => CACHED [final_image  1/22] COPY ./scripts/install_packages /project/avalon/scripts/                                  0.0s
 => CACHED [final_image  2/22] RUN if [ "bionic" = "centos" ] ; then       dnf remove -y python3-pip;       packages="o  0.0s
 => CACHED [final_image  3/22] RUN packages="git";     pip_packages="json-rpc web3 py-solc-x nose2 virtualenv fastapi==  0.0s
 => CACHED [final_image  4/22] WORKDIR /opt/intel/                                                                       0.0s
 => CACHED [final_image  5/22] RUN packages="wget tar libsgx-dcap-default-qpl libsgx-dcap-quote-verify";   if [ "bionic  0.0s
 => ERROR [final_image  6/22] RUN python3 -m solcx.install v0.5.15                                                       0.5s
 => CACHED [common_crypto_utils_image  1/22] COPY ./scripts/install_packages /project/avalon/scripts/                    0.0s
 => CACHED [common_crypto_utils_image  2/22] RUN packages="swig";     if [ "bionic" = "centos" ] ; then       packages=  0.0s
 => CACHED [openssl_image 3/6] RUN packages="ca-certificates pkg-config make wget tar";     if [ "bionic" = "centos" ]   0.0s
 => CACHED [openssl_image 4/6] WORKDIR /tmp                                                                              0.0s
 => CACHED [openssl_image 5/6] RUN OPENSSL_VER=1.1.1g  && wget https://www.openssl.org/source/openssl-$OPENSSL_VER.tar.  0.0s
 => CACHED [openssl_image 6/6] RUN if [ "bionic" = "bionic" ] ; then       mkdir /usr/local/lib64;     fi                0.0s
 => CACHED [common_crypto_utils_image  3/22] COPY --from=openssl_image /usr/local/ssl /usr/local/ssl                     0.0s
 => CACHED [common_crypto_utils_image  4/22] COPY --from=openssl_image /usr/local/bin /usr/local/bin                     0.0s
 => CACHED [common_crypto_utils_image  5/22] COPY --from=openssl_image /usr/local/include /usr/local/include             0.0s
 => CACHED [common_crypto_utils_image  6/22] COPY --from=openssl_image /usr/local/lib /usr/local/lib                     0.0s
 => CACHED [common_crypto_utils_image  7/22] COPY --from=openssl_image /usr/local/lib64 /usr/local/lib64                 0.0s
 => CACHED [common_crypto_utils_image  8/22] RUN ldconfig  && ln -s /etc/ssl/certs/* /usr/local/ssl/certs/               0.0s
 => CACHED [common_cpp_image  3/16] RUN packages="pkg-config make cmake wget tar";     if [ "bionic" = "centos" ] ; the  0.0s
 => CACHED [common_cpp_image  4/16] COPY --from=openssl_image /usr/local/ssl /usr/local/ssl                              0.0s
 => CACHED [common_cpp_image  5/16] COPY --from=openssl_image /usr/local/bin /usr/local/bin                              0.0s
 => CACHED [common_cpp_image  6/16] COPY --from=openssl_image /usr/local/include /usr/local/include                      0.0s
 => CACHED [common_cpp_image  7/16] COPY --from=openssl_image /usr/local/lib /usr/local/lib                              0.0s
 => CACHED [common_cpp_image  8/16] COPY --from=openssl_image /usr/local/lib64 /usr/local/lib64                          0.0s
 => CACHED [common_cpp_image  9/16] RUN ldconfig  && ln -s /etc/ssl/certs/* /usr/local/ssl/certs/                        0.0s
 => CACHED [common_cpp_image 10/16] RUN mkdir -p /opt/intel/                                                             0.0s
 => CACHED [common_cpp_image 11/16] WORKDIR /opt/intel/                                                                  0.0s
 => CACHED [common_cpp_image 12/16] RUN SGX_SDK_FILE=sgx_linux_x64_sdk_2.11.100.2.bin   && wget https://download.01.org  0.0s
 => CACHED [common_cpp_image 13/16] RUN packages="libsgx-dcap-ql-dev libsgx-dcap-quote-verify libsgx-dcap-quote-verify-  0.0s
 => CACHED [common_cpp_image 14/16] COPY ./common/cpp /project/avalon/common/cpp                                         0.0s
 => CACHED [common_cpp_image 15/16] WORKDIR /project/avalon/common/cpp                                                   0.0s
 => CACHED [common_cpp_image 16/16] RUN mkdir -p build   && cd build   && cmake .. -DUNTRUSTED_ONLY=1   && make          0.0s
 => CACHED [common_crypto_utils_image  9/22] COPY --from=common_cpp_image /project/avalon/common/cpp/build /project/ava  0.0s
 => CACHED [common_crypto_utils_image 10/22] COPY VERSION /project/avalon/                                               0.0s
 => CACHED [common_crypto_utils_image 11/22] COPY ./bin /project/avalon/bin                                              0.0s
 => CACHED [common_crypto_utils_image 12/22] COPY ./common/cpp /project/avalon/common/cpp                                0.0s
 => CACHED [common_crypto_utils_image 13/22] WORKDIR /opt/intel                                                          0.0s
 => CACHED [common_crypto_utils_image 14/22] RUN packages="libsgx-dcap-ql-dev libsgx-dcap-quote-verify libsgx-dcap-quot  0.0s
 => CACHED [common_crypto_utils_image 15/22] COPY ./common/crypto_utils /project/avalon/common/crypto_utils              0.0s
 => CACHED [common_crypto_utils_image 16/22] WORKDIR /project/avalon/common/crypto_utils                                 0.0s
 => CACHED [common_crypto_utils_image 17/22] RUN echo "Building Avalon Common Crypto Python\n"  && make                  0.0s
 => CACHED [common_crypto_utils_image 18/22] COPY ./common/verify_report_utils/ /project/avalon/common/verify_report_ut  0.0s
 => CACHED [common_crypto_utils_image 19/22] WORKDIR /project/avalon/common/verify_report_utils/ias                      0.0s
 => CACHED [common_crypto_utils_image 20/22] RUN echo "Building Avalon Verify IAS Report Utils\n"  && make               0.0s
 => CACHED [common_crypto_utils_image 21/22] WORKDIR /project/avalon/common/verify_report_utils/dcap                     0.0s
 => CACHED [common_crypto_utils_image 22/22] RUN echo "Building Avalon Verify DCAP Report Utils\n"  && make              0.0s
------
 > [final_image  6/22] RUN python3 -m solcx.install v0.5.15:
#14 0.472 /usr/bin/python3: Error while finding module specification for 'solcx.install' (ModuleNotFoundError: No module named 'solcx')
------
executor failed running [/bin/sh -c python3 -m solcx.install v0.5.15]: exit code: 1
ERROR: Service 'avalon-shell' failed to build : Build failed
```

**Comment by SamYuan1990** [comment]
workaround solution:
```
RUN apt-get install -y python3-pip
RUN pip3 install py-solc-x
```

**Comment by SamYuan1990** [comment]
Passed local test，but still missing some python libs in test container.

```
root@1848e0ae1f69:/project/avalon/examples/apps/generic_client# ./generic_client.py --workload_id "heart-disease-eval" \
>     --in_data "Data: 25 10 1 67 102 125 1 95 5 10 1 11 36 1" -o
Traceback (most recent call last):
  File "./generic_client.py", line 23, in <module>
    from direct_model_generic_client import DirectModelGenericClient
  File "/project/avalon/examples/apps/generic_client/direct_model_generic_client.py", line 21, in <module>
    from avalon_sdk.connector.blockchains.ethereum.ethereum_worker_registry_list \
  File "/usr/local/lib/python3.6/dist-packages/avalon_sdk/connector/blockchains/ethereum/ethereum_worker_registry_list.py", line 23, in <module>
    from avalon_sdk.connector.blockchains.ethereum.ethereum_wrapper \
  File "/usr/local/lib/python3.6/dist-packages/avalon_sdk/connector/blockchains/ethereum/ethereum_wrapper.py", line 21, in <module>
    import web3

```
